CREATE USER OMER IDENTIFIED BY CAPUR;

GRANT CONNECT, RESOURCE TO OMER;

GRANT SELECT ON REGIONS TO OMER;
GRANT INSERT ON REGIONS TO OMER;

GRANT UPDATE, DELETE ON REGIONS TO OMER;

GRANT UPDATE, DELETE ON REGIONS TO OMER WITH GRANT OPTION;
 (OMER, BASKASINA DA YETKI VEREBILIR HALE GELIR)

-DBA YETKILI KISININ (MEHMET) KIMLERE NE YETKI VERDIGI

SELECT * FROM USER_TAB_PRIVS_MADE;

-OMER KULLANICISINDAN REGION TABLOSUNDA SELECT YETKISININ ALINMASI

REVOKE SELECT ON REGIONS FROM OMER;

-DIGER YETKILER DE ALINIRSA

REVOKE INSERT, DELETE, UPDATE ON REGIONS FROM OMER;

-VERITABANINDAKI TUM KULLANICILARA SELECT YETKISI VERMEK

GRANT SELECT ON REGIONS TO PUBLIC; (COK DOGRU DEGIL)

