-- ROLES

CREATE ROLE R_SELUPT; --UPDATE ROLU OLUSTURULDU
CREATE ROLE R_INSDEL; -- INSERT VE DELETE ROLU OLUSTURULDU

GRANT SELECT, UPDATE ON REGIONS TO R_SELUPT; ROLLERE ATAMA YAPILIR

GRANT INSERT, DELETE ON REGIONS TO R_INSDEL;

GRANT R_SELUPT TO ILKNUR;  --ROLLERE SAHIP OLACAK OLANLAR YAZILIR
GRANT R_INSDEL TO OMER;

REVOKE UPDATE ON REGIONS FROM R_SELUPT; 
(ROLLER ALINIRKEN KISI KISI YAZMAKYERINE TOPLUCA ALINMIS OLUR)

REVOKE R_INSDEL FROM OMER; - OMER DEN ROL ALINIR

DROP ROLE R_INSDEL; - ROL TAMAMEN SILINIR (SADECE OLUSTURAN SILEBILIR)
-OMER KULLANICISI 

SET ROLE R_INSDEL; - ROL KABUL EDILIR

INSERT INTO MEHMET.REGIONS VALUES (7,'ABC');

-ILKNUR KULLANICISI

SET ROLE R_SELUPT; - ROL KABUL EDILIR

SELECT * FROM MEHMET.REGIONS;

UPDATE MEHMET.REGIONS
SET
REGION_NAME = 'XYZ'
WHERE REGION_ID = 7;
COMMIT;